alter table	ZIPCODE_INFO ALTER COLUMN ZIP_CODE VARCHAR(5);
ALTER TABLE ZIPCODE_INFO ALTER COLUMN CITY VARCHAR(25);
ALTER TABLE ZIPCODE_INFO ADD STATE VARCHAR(2);

alter TABLE INSTRUCTION_INFO ALTER COLUMN INSTRUCTOR_ID NUMERIC(8,0);
ALTER TABLE INSTRUCTION_INFO ALTER COLUMN INSTRUCTOR_LAST_NAME VARCHAR(25);
ALTER TABLE INSTRUCTION_INFO ALTER COLUMN INSTRUCTOR_FIRST_NAME VARCHAR(25);
ALTER TABLE INSTRUCTION_INFO ADD STREET_ADDRESS VARCHAR (50);
ALTER TABLE INSTRUCTION_INFO ADD ZIPCODE VARCHAR(5);

ALTER TABLE COURSE_INFO ALTER COLUMN COURSE_NO NUMERIC(8,0);
ALTER TABLE COURSE_INFO ADD COURSE_NAME VARCHAR(50);
ALTER TABLE COURSE_INFO ADD COURSE_PREREQUISITE NUMERIC(8,0);
ALTER TABLE COURSE_INFO ALTER COLUMN COST NUMERIC(9,2);

ALTER TABLE STUDENT_INFO ALTER COLUMN STUDENT_ID NUMERIC(8,0);
ALTER TABLE STUDENT_INFO ALTER COLUMN STUDENT_FIRST_NAME VARCHAR(25);
ALTER TABLE STUDENT_INFO ALTER COLUMN STUDENT_LAST_NAME VARCHAR(25);
ALTER TABLE STUDENT_INFO ADD STUDENT_ADDRESS VARCHAR(50);
ALTER TABLE STUDENT_INFO ADD ZIP_CODE VARCHAR (5);

ALTER TABLE SECTION_INFO ALTER COLUMN SECTION_ID NUMERIC(8,0);
ALTER TABLE SECTION_INFO ALTER COLUMN COURSE_NO NUMERIC(8,0);
ALTER TABLE SECTION_INFO ALTER COLUMN SECTION_NO NUMERIC(3,0);
ALTER TABLE SECTION_INFO ALTER COLUMN INSTRUCTOR_ID NUMERIC(8,0);
ALTER TABLE SECTION_INFO ADD LOCATION VARCHAR(50);
ALTER TABLE SECTION_INFO ADD CAPACITY NUMERIC(3,0);


ALTER TABLE ENROLLMENT_INFO ALTER COLUMN STUDENT_ID NUMERIC(8,0);
ALTER TABLE ENROLLMENT_INFO ALTER COLUMN SECTION_ID NUMERIC(8,0);
ALTER TABLE ENROLLMENT_INFO ADD ENROLLMENT_DATE DATE;

ALTER TABLE GRADE_INFO ALTER COLUMN STUDENT_ID NUMERIC (8,0);
ALTER TABLE GRADE_INFO ALTER COLUMN SECTION_ID NUMERIC(8,0);
ALTER TABLE GRADE_INFO ADD GRADE_TYPE_CODE CHAR(2);
ALTER TABLE GRADE_INFO ALTER COLUMN GRADE_CODE_OCCURANCE NUMERIC(38,0);
ALTER TABLE GRADE_INFO ADD NUMERIC_GRADE NUMERIC(3,0);